# Generated by Django 6.1 on 2026-08-12 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone/WhatsApp')),
                ('instagram_handle', models.CharField(blank=True, max_length=50, verbose_name='Instagram (@)')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Data e Hora')),
                ('description', models.TextField(verbose_name='Detalhes da Tatuagem (Tamanho, local, ideia)')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='references/', verbose_name='Imagem de Referência')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente (Aguardando Aprovação)'), ('CONFIRMED', 'Confirmado'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Estimado (R$)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='scheduling.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['date_time'],
            },
        ),
    ]
