# Generated by Django 6.1 on 2026-08-12 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Final Cobrado (R$)')),
                ('payment_method', models.CharField(choices=[('PIX', 'PIX'), ('CREDIT', 'Cartão de Crédito'), ('DEBIT', 'Cartão de Débito'), ('CASH', 'Dinheiro')], max_length=20, verbose_name='Método de Pagamento')),
                ('date_completed', models.DateTimeField(auto_now_add=True, verbose_name='Data de Conclusão')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_record', to='scheduling.appointment', verbose_name='Agendamento')),
            ],
            options={
                'verbose_name': 'Registro de Serviço',
                'verbose_name_plural': 'Registros de Serviços',
                'ordering': ['-date_completed'],
            },
        ),
    ]
