# Generated by Django 6.0.7 on 2026-08-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('tattoo', 'Tatuagem'), ('piercing', 'Piercing')], default='tattoo', max_length=20, verbose_name='Categoria')),
                ('image', models.ImageField(upload_to='portfolio_images/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
            ],
            options={
                'verbose_name': 'Trabalho',
                'verbose_name_plural': 'Trabalhos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Tattoo',
        ),
    ]
