# Generated by Django 6.0.7 on 2026-08-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_work_delete_tattoo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tatuador', max_length=100, verbose_name='Nome Artístico')),
                ('bio', models.TextField(verbose_name='Biografia (Sobre Mim)')),
                ('profile_image', models.ImageField(upload_to='artist_images/', verbose_name='Foto de Perfil')),
            ],
            options={
                'verbose_name': 'Perfil do Artista',
                'verbose_name_plural': 'Perfil do Artista',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título da Certificação')),
                ('image', models.ImageField(upload_to='certifications/', verbose_name='Imagem do Certificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
            ],
            options={
                'verbose_name': 'Certificação',
                'verbose_name_plural': 'Certificações',
                'ordering': ['-created_at'],
            },
        ),
    ]
